print('vamos fazer um reconhecimento, siga o que se pede')
r1=input("digite algo! ")
print('é um numero',r1.isnumeric())
print('e uma letra',r1.isalpha())
print('e uma letra  mauscula? ',r1.isupper())
print('é minuscula?',r1.islower())